### ISSUE TITLE
Ensemble B&B - "Intro to boosting.pdf” - links do not work

### ISSUE THREAD

**Issue by pdlje82** [udacity/mlnd_issues_tracker#10]
Hi,

in lesson 16 (Ensemble B&B) the document links in ["Intro to boosting.pdf”](https://storage.googleapis.com/supplemental_media/udacityu/367378584/Intro%20to%20Boosting.pdf)  do not work. Maybe because the layout of the udacity website changed recently?

**Comment by adarsh0806** [comment]
The link you have shared does seem to work. Here is a new link --> https://www.scribd.com/document/346938100/Boosting
