### ISSUE TITLE
Video 21 is missing

### ISSUE THREAD

**Issue by drewkerwin** [udacity/mlnd_issues_tracker#13]
Stochastic Gradient Descent video is missing from Deep Learning section of Course

**Comment by drewkerwin** [comment]
https://classroom.udacity.com/nanodegrees/nd009/parts/e5258169-7f53-4da8-b3f5-ad0b3ef2fb42/modules/27d9b09f-7ff5-4011-a8a1-1d3532bb571e/lessons/9a3633e0-be9e-4fe5-a0bc-acfbe675b968/concepts/63798118390923

**Comment by adarsh0806** [comment]
Checked the video, it looks like it is public and visible. Can you show a screenshot of what you see?

**Comment by drewkerwin** [comment]
All information is here: https://discussions.udacity.com/t/information-is-missing-in-deep-learning/243041 <https://discussions.udacity.com/t/information-is-missing-in-deep-learning/243041>
