### ISSUE TITLE
Quiz Lesson6: possible typo in the solution

### ISSUE THREAD

**Issue by DrAnaximandre** [udacity/mlnd_issues_tracker#21]
There might be a typo in the solution.py file, l13 of the quiz (2) of Lesson 6 : "Regression Metrics".

The scikit help specifies that the signature of the function is (y_true, y_predicted) (and other arguments that are not of interest here), . However this is not the case in the l13 of solution.py (it is reversed).

The R2 metric is sensitive to the order of the parameters.

**Comment by fixingitnow** [comment]
no longer valid issue
