### ISSUE TITLE
Module: Deep Learning - Lesson 1-30 - Feedforward typos

### ISSUE THREAD

**Issue by antnh6** [udacity/mlnd_issues_tracker#24]
In the last video, at 0:50, the top two equations  should have been:

h<sub>1</sub> = W<sub>11</sub><sup>(1)</sup>\*x<sub>1</sub> + **W<sub>21</sub><sup>(1)</sup>\*x<sub>2</sub> + W<sub>31</sub><sup>(1)</sup>**

and 

h<sub>2</sub> = **W<sub>12</sub><sup>(1)</sup>\*x<sub>1</sub> + W<sub>22</sub><sup>(1)</sup>\*x<sub>2</sub> + W<sub>32</sub><sup>(1)</sup>**

The subscripts are messed up a bit, and I have corrected them in bold.
Please refer to [here](https://discussions.udacity.com/t/feedforward-possible-typos/320340) if you have any questions. Thanks!

**Comment by fixingitnow** [comment]
content has been updated.
