### ISSUE TITLE
Lesson 3 More Clustering: Expectation Maximization slide error

### ISSUE THREAD

**Issue by ghost** [udacity/mlnd_issues_tracker#27]
In the video, when normalizing P(M_j, x_i) (E[z_ij] in the video), the sum of the normalizing term is over the samples from the dataset, and it should be over the means of the k clusters. In other words, the i should be changed to j in the image below.

![lesson3error](https://user-images.githubusercontent.com/15941912/29742194-dd54d62c-8a7a-11e7-978c-39c73c102357.png)

**Comment by vojavocni** [comment]
In the video, when normalizing P(M_j, x_i) (E[z_ij] in the video), the sum of the normalizing term is over the samples from the dataset, and it should be over the means of the k clusters.

![LEsson3Error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a182a66eeb5410d88fc937/125516c66e82c728ace21e0d46c4b189308d8dfaaafbad4cb61fbcd6395428792c07b7692ac7b670e74023580c574ead435d5816f9ad8929a0e33822835819f1c32f0e2a92624cf5f2d75dad0ba824894686bcbd8f4cc3ef3822e58d874f3e161755.png)

**Comment by fixingitnow** [comment]
no longer valid in the revised version.
