### ISSUE TITLE
Lesson 3, point 4.: broken link

### ISSUE THREAD

**Issue by ClaraDePaiva** [udacity/mlnd_issues_tracker#28]
Hi!,

This is a small issue regarding portuguese content: there is a broken link in the  text that advertises the portuguese community forum, on Lesson 3, point 4.

The broken link...
![broken link](https://user-images.githubusercontent.com/33913575/33152040-ddee0036-cfda-11e7-9bf5-b19d4b278824.jpg)
... and where it comes fom:
![where it comes from](https://user-images.githubusercontent.com/33913575/33152043-e23ee132-cfda-11e7-9559-b500c086cc3e.jpg)

**Comment by fixingitnow** [comment]
no longer valid issue / issue very old.
