### ISSUE TITLE
Results of optimal classifier exercise are incorrect

### ISSUE THREAD

**Issue by drewkerwin** [udacity/mlnd_issues_tracker#3]

**Comment by drewkerwin** [comment]
there appears to be a bug in the auto-grader

sample_memo = '''
Milt, we're gonna need to go ahead and move you downstairs into storage B. We have some new people coming in, and we need all the space we can get. So if you could just go ahead and pack up your stuff and move it down there, that would be terrific, OK?
Oh, and remember: next Friday... is Hawaiian shirt day. So, you know, if you want to, go ahead and wear a Hawaiian shirt and jeans.
Oh, oh, and I almost forgot. Ahh, I'm also gonna need you to go ahead and come in on Sunday, too...
Hello Peter, whats happening? Ummm, I'm gonna need you to go ahead and come in tomorrow. So if you could be here around 9 that would be great, mmmk... oh oh! and I almost forgot ahh, I'm also gonna need you to go ahead and come in on Sunday too, kay. We ahh lost some people this week and ah, we sorta need to play catch up.
'''
{The word 'here' does not appear two words after 'would' in the above text. Please advise.
You guessed {"I'm": 1} after forgot., where we guessed ["I'm"]. 
Here was our whole calculation: {"I'm": 1} [[1, "I'm"]]
You guessed {'terrific,': 1, 'great,': 1} after would, where we guessed ['terrific,', 'here', 'great,'].
Here was our whole calculation: {'terrific,': 2, 'here': 2, 'great,': 2} [[2, 'terrific,'], [2, 'here'], [2, 'great,']]
You guessed {'is': 1} after next, where we guessed ['is'].
Here was our whole calculation: {'is': 1} [[1, 'is']]

Additionally, 'would' is followed by 'terrific' and 'great' once apiece... so the score on that test is also wrong

**Comment by adarsh0806** [comment]
Could you give us the classroom link to this as well? Thanks!
