### ISSUE TITLE
Lost Access to MLND

### ISSUE THREAD

**Issue by NitinMahajan1** [udacity/mlnd_issues_tracker#30]
I am waiting to be given access to my MLND. 
After repeated reminders, I have not got access/response to below email- (I have replied that I am OK to be re-enrolled to the older version) 

Hi Nitin,

I'm sorry to say that we are not leveraging past payments you have made toward this program because this will grant you 6 months of access. The discount of $799 as opposed to $999 is the benefit of this switch, but we do not deduct the past payments you have made toward this new version. Students in your circumstances are meant to pay $799 instead of $999, but not less than that.

My apologies for moving too quickly on this, I did understand your past emails where you said you agreed to the terms of this switch to mean that you were ready to switch regardless of the payment details.

I can have you re-enrolled in the old version of your Machine Learning Engineer Nanodegree program instead of switching you so you will continue with the older content paying $199/month instead of giving you access to the new version with the new payment model.

I am forward you back to the Machine Learning Engineer Nanodegree program to have you re-enrolled in your old content version.

Thank you for your patience and understanding,

Ryan

**Comment by fixingitnow** [comment]
no longer an issue.
