### ISSUE TITLE
3. Supervised Learning - Lesson 15: Ensemble B&B - 5. Ensemble Learning: An Example

### ISSUE THREAD

**Issue by miguelangel** [udacity/mlnd_issues_tracker#42]
Hi!

I think I have caught a small typo in the vide.

At second 27 it refers to 9 points when effectively it looks like there are only 8 points.

Please find below the video I am referring to:

https://youtu.be/Cn7StaXU_8o?t=27s

It also mentions that 8 points are going to be used to learn from then, when the correct number should be 7.

Hope it helps,

Miguel Ángel

**Comment by fixingitnow** [comment]
video no longer referred in the content.
