### ISSUE TITLE
Two issues in my profile.

### ISSUE THREAD

**Issue by ArbinTimilsina** [udacity/mlnd_issues_tracker#43]
For some reason, my LinkedIn, GitHub, Twitter and resume are not displayed in the public profile and neither is my email address. However, they show up correctly at my (private, editable) profile. Is this a bug or do I need to change some settings somewhere? Also, at the top, it says "92% COMPLETED Add a visible, personal project". However, I have already added a visible, personal project. Another bug, maybe?

**Comment by fixingitnow** [comment]
no longer valid issue
