### ISSUE TITLE
Regarding Career: Job Search Strategies

### ISSUE THREAD

**Issue by ArbinTimilsina** [udacity/mlnd_issues_tracker#44]
I have successfully completed the Projects: Refine Your Entry-Level Resume and Cover Letter Review. However, I don't see a check-mark in the "Career: Job Search Strategies" part of the Core Curriculum. This makes it seem like I have to do the Projects: Refine Your Career Change Resume and Refine Your Prior Industry Experience Resume as well. I hope that's not the case? It would be nice to see a check-mark in the "Career: Job Search Strategies" when one of the three Resumes is successfully completed.

**Comment by fixingitnow** [comment]
no longer valid issue
