### ISSUE TITLE
Links in MLND not working

### ISSUE THREAD

**Issue by sshaikh08** [udacity/mlnd_issues_tracker#52]

**Comment by sshaikh08** [comment]
the links of the following page are not working:

https://classroom.udacity.com/nanodegrees/nd009t/parts/278ce043-1d6a-4695-9d26-90459706fda9/modules/b7517613-1d51-47eb-8147-d00044443e5d/lessons/318fc61b-fd70-43b7-a4e2-a3ed92719589/concepts/426a4c0c-ac7b-451b-a35f-7bfb14f162f7

**Comment by fixingitnow** [comment]
updated links, if issue persists please use instructions from https://github.com/udacity/mlnd_issues_tracker/blob/master/Readme.md to raise the issue.
