### ISSUE TITLE
External link for pandas numpy not working

### ISSUE THREAD

**Issue by sunilp** [udacity/mlnd_issues_tracker#54]

**Comment by sunilp** [comment]
For MLND, In lesson 1, section 4, Numpy and Pandas, the external links to other classrooms have been given, but on click of it, it says no permission.

**Comment by fixingitnow** [comment]
updated links, if issue persists please use instructions from https://github.com/udacity/mlnd_issues_tracker/blob/master/Readme.md to raise the issue.
