### ISSUE TITLE
Invalid URL link to paper for Taxi-v2 mini project

### ISSUE THREAD

**Issue by huang-haijie** [udacity/mlnd_issues_tracker#58]
In Reinforcement Learning -> Lesson 7: Solve OpenAI Gym's Taxi-v2 task -> Introduction, the URL link to the paper on the Taxi environment is no longer valid, it gets redirected to the home page of www.jair.org.

**Comment by fixingitnow** [comment]
The link looks good now, https://arxiv.org/pdf/cs/9905014.pdf here is the link in case of any confusion.
