### ISSUE TITLE
Project submission confusing

### ISSUE THREAD

**Issue by hajko** [udacity/mlnd_issues_tracker#59]
There is (sometimes) a submit button in the bottom right corner of the Jupyter workspace. Clicking this does not allow you to attach a zip file. The instructions regarding how to submit should be clarified. I am still unsure if submitting by using the bottom right submit button plus uploading the html file is acceptable. Or whether one must upload a zip file containing the notebook + html file.

**Comment by fixingitnow** [comment]
Hi @hajko , When your source of submission is through workspace then we do not expect you to attach any zip file,
