### ISSUE TITLE
Missing bottleneck features in Deep Learning dog project

### ISSUE THREAD

**Issue by wgilpin** [udacity/mlnd_issues_tracker#60]
I have VGG16 features in the bottleneck_features directory, but I am required by the project (and rubric) to use VGG-19, ResNet-50, Inception, or Xception. Uploading them is not realistic as they are ~1Gb files each.

**Comment by fixingitnow** [comment]
You Should be using those models, but aren't expected to upload it. Use of .gitignore to exclude the files that are larger than a certain limit is a good practice.
