### ISSUE TITLE
content typo

### ISSUE THREAD

**Issue by alifars** [udacity/mlnd_issues_tracker#62]
in confusion matrix  quiz, at the bottom of the page where it explains type 1 and type 2 errors, it should be false negatives, instead of true negatives

actual:
Type 1 and Type 2 Errors
Sometimes in the literature, you'll see False Positives and True Negatives as Type 1 and Type 2 errors. Here is the correspondence:

Expected:
Sometimes in the literature, you'll see False Positives and False Negatives

**Comment by fixingitnow** [comment]
Content has been updated, no longer an issue. This closes #62.
