### ISSUE TITLE
Error in DL module, lesson 1, Feedforward

### ISSUE THREAD

**Issue by Gaston-Udacity** [udacity/mlnd_issues_tracker#68]
Student input: "I think there is an error in the Deep Learning module, lesson 1 (introduction to neural networks), unit 33 (feedforward), first video: the matrix shown starting at timestamp 2:52 has the wrong shape. It is showing a matrix with 3 rows and 2 columns. It should be 2 rows and 4 columns. Otherwise the matrix multiplication does not work. The whole matrix is later shown correctly in unit 34 (backpropagation), 4th video, starting at about timestamp 1:31."

**Comment by fixingitnow** [comment]
Could you give the classroom link to this as well? Thanks!

**Comment by fixingitnow** [comment]
Issue is assigned to @luisguiserrano.

**Comment by fixingitnow** [comment]
matrix images are blank now.
