### ISSUE TITLE
Quiz: Compute Mean Squared Error

### ISSUE THREAD

**Issue by msondkar** [udacity/mlnd_issues_tracker#7]
Could you please make the following amendments just to change the print statement for having 'mean squared error' instead of 'mean absolute error'.

**From** 
reg1 = DecisionTreeRegressor()
reg1.fit(X, y)
print "Decision Tree mean absolute error: {:.2f}".format(mse(y, reg1.predict(X)))

reg2 = LinearRegression()
reg2.fit(X, y)
print "Linear regression mean absolute error: {:.2f}".format(mse(y, reg2.predict(X)))

**To**

reg1 = DecisionTreeRegressor()
reg1.fit(X, y)
print "Decision Tree mean squared error: {:.2f}".format(mse(y, reg1.predict(X)))

reg2 = LinearRegression()
reg2.fit(X, y)
print "Linear regression mean squared error: {:.2f}".format(mse(y, reg2.predict(X)))

**Comment by adarsh0806** [comment]
Could you give the classroom link to this as well? Thanks!

**Comment by msondkar** [comment]
Classroom link https://classroom.udacity.com/nanodegrees/nd009/parts/3d764b58-dc1f-4f7b-b0e1-6b60359e0af4/modules/f8617d67-d59a-4aec-a8fd-050d60c2b7eb/lessons/7967566162/concepts/80260579442589030923#

**Comment by fixingitnow** [comment]
fixed.
